import { colors, radii } from './theme.ts';
import { StyleSheet } from 'react-native';

export const aliasReviewStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: colors.backdrop,
    padding: 16,
  },
  modalCard: {
    maxHeight: '92%',
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  title: {
    fontSize: 21,
    lineHeight: 28,
    fontWeight: '800',
    color: colors.primaryStrong,
    marginBottom: 12,
  },
  productCard: {
    backgroundColor: colors.lilac,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.card,
    padding: 12,
    marginBottom: 8,
  },
  productName: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  productDetails: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.text,
    marginTop: 3,
  },
  content: {
    flexShrink: 1,
  },
  contentInner: {
    paddingBottom: 4,
  },
  fieldLabel: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: colors.text,
    marginTop: 8,
    marginBottom: 6,
  },
  input: {
    minHeight: 54,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.disabled,
    borderRadius: radii.field,
    paddingHorizontal: 12,
    fontSize: 17,
    lineHeight: 23,
    color: colors.primaryStrong,
  },
  helpText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.primaryMuted,
    marginTop: 8,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  statusText: {
    fontSize: 15,
    lineHeight: 21,
    color: colors.primary,
  },
  proposalCard: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.card,
    padding: 12,
    marginTop: 14,
  },
  proposalTitle: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
    color: colors.primaryStrong,
    marginBottom: 8,
  },
  proposalRow: {
    marginBottom: 7,
  },
  proposalLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.muted,
    fontWeight: '600',
  },
  proposalValue: {
    fontSize: 16,
    lineHeight: 23,
    color: colors.primaryStrong,
    fontWeight: '700',
  },
  conflictWarning: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningOutline,
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
  },
  conflictTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: colors.warning,
  },
  conflictText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.warning,
    marginTop: 4,
  },
  conflictProduct: {
    fontSize: 15,
    lineHeight: 21,
    color: colors.warning,
    fontWeight: '600',
    marginTop: 5,
  },
  errorBox: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  errorText: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '600',
    color: colors.error,
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  button: {
    minWidth: '30%',
    minHeight: 52,
    flexGrow: 1,
    paddingHorizontal: 10,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  cancelButtonText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: colors.primaryMuted,
  },
  reviewButton: {
    backgroundColor: colors.primary,
  },
  confirmButton: {
    backgroundColor: colors.success,
  },
  primaryButtonText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: colors.surface,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
});
