import { StyleSheet } from 'react-native';

export const aliasReviewStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    padding: 16,
  },
  modalCard: {
    maxHeight: '92%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  title: {
    fontSize: 21,
    lineHeight: 28,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 12,
  },
  productCard: {
    backgroundColor: '#f0f9ff',
    borderWidth: 1,
    borderColor: '#bae6fd',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  productName: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: '#0c4a6e',
  },
  productDetails: {
    fontSize: 15,
    lineHeight: 22,
    color: '#334155',
    marginTop: 3,
  },
  content: {
    flexShrink: 1,
  },
  contentInner: {
    paddingBottom: 4,
  },
  fieldLabel: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#334155',
    marginTop: 8,
    marginBottom: 6,
  },
  input: {
    minHeight: 54,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#94a3b8',
    borderRadius: 9,
    paddingHorizontal: 12,
    fontSize: 17,
    lineHeight: 23,
    color: '#0f172a',
  },
  helpText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#475569',
    marginTop: 8,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  statusText: {
    fontSize: 15,
    lineHeight: 21,
    color: '#0369a1',
  },
  proposalCard: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    padding: 12,
    marginTop: 14,
  },
  proposalTitle: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 8,
  },
  proposalRow: {
    marginBottom: 7,
  },
  proposalLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#64748b',
    fontWeight: '600',
  },
  proposalValue: {
    fontSize: 16,
    lineHeight: 23,
    color: '#0f172a',
    fontWeight: '700',
  },
  conflictWarning: {
    backgroundColor: '#fffbeb',
    borderColor: '#fcd34d',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
  },
  conflictTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: '#92400e',
  },
  conflictText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#78350f',
    marginTop: 4,
  },
  conflictProduct: {
    fontSize: 15,
    lineHeight: 21,
    color: '#451a03',
    fontWeight: '600',
    marginTop: 5,
  },
  errorBox: {
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fca5a5',
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  errorText: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '600',
    color: '#b91c1c',
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  button: {
    minWidth: '30%',
    minHeight: 52,
    flexGrow: 1,
    paddingHorizontal: 10,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  cancelButtonText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#475569',
  },
  reviewButton: {
    backgroundColor: '#0284c7',
  },
  confirmButton: {
    backgroundColor: '#15803d',
  },
  primaryButtonText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: '#ffffff',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
});
