import { StyleSheet } from 'react-native';

export const askPriceStyles = StyleSheet.create({
  container: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
  },
  subtitle: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 2,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 8,
  },
  input: {
    flex: 1,
    minHeight: 52,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#1e293b',
  },
  clearButton: {
    minHeight: 52,
    paddingHorizontal: 14,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  clearButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
  },
  centered: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  helperText: {
    marginTop: 8,
    fontSize: 14,
    color: '#64748b',
  },
  cardSuccess: {
    backgroundColor: '#f0fdf4',
    borderWidth: 2,
    borderColor: '#22c55e',
    borderRadius: 16,
    padding: 20,
    marginTop: 8,
  },
  productBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#dcfce7',
    color: '#15803d',
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginBottom: 8,
  },
  productName: {
    fontSize: 24,
    fontWeight: '800',
    color: '#14532d',
  },
  productMeta: {
    fontSize: 16,
    color: '#166534',
    marginTop: 4,
  },
  priceContainer: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#bbf7d0',
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
  },
  priceLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#166534',
  },
  priceValue: {
    fontSize: 32,
    fontWeight: '900',
    color: '#15803d',
  },
  ambiguousContainer: {
    marginTop: 8,
  },
  ambiguousTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 12,
  },
  choiceCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    minHeight: 60,
  },
  choiceInfo: {
    flex: 1,
  },
  choiceName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1e293b',
  },
  choiceMeta: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 2,
  },
  choicePrice: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0284c7',
    marginLeft: 12,
  },
  cardUnknown: {
    backgroundColor: '#fffbeb',
    borderWidth: 1.5,
    borderColor: '#f59e0b',
    borderRadius: 16,
    padding: 20,
    marginTop: 8,
  },
  unknownTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#92400e',
    marginBottom: 6,
  },
  unknownText: {
    fontSize: 15,
    color: '#78350f',
    marginBottom: 8,
  },
  unknownHint: {
    fontSize: 13,
    color: '#b45309',
    lineHeight: 18,
  },
  emptyContainer: {
    paddingVertical: 48,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 15,
    color: '#94a3b8',
    textAlign: 'center',
    paddingHorizontal: 24,
    lineHeight: 22,
  },
});
