import { StyleSheet } from 'react-native';
import { colors, radii } from './theme.ts';

export const askPriceStyles = StyleSheet.create({
  container: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 40,
    backgroundColor: colors.background,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: colors.primary,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 15,
    color: colors.muted,
    marginTop: 4,
    lineHeight: 22,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 56,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.outline,
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginBottom: 12,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    minHeight: 48,
    fontSize: 16,
    color: colors.text,
    paddingVertical: 8,
  },
  clearButton: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearButtonIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surfaceSoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  correctionLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    paddingVertical: 10,
    marginBottom: 12,
  },
  correctionText: {
    flexShrink: 1,
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
  },
  cardSuccess: {
    backgroundColor: colors.lilac,
    borderRadius: 26,
    padding: 22,
    marginTop: 4,
  },
  resultHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.outline,
    marginBottom: 16,
  },
  productName: {
    fontSize: 36,
    fontWeight: '900',
    color: colors.primary,
    lineHeight: 42,
    flexWrap: 'wrap',
  },
  productMeta: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.primaryMuted,
    marginTop: 6,
    flexWrap: 'wrap',
  },
  priceValue: {
    fontSize: 58,
    fontWeight: '900',
    color: colors.primary,
    letterSpacing: -1,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  foundBadge: {
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.accent,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 6,
    marginTop: 16,
  },
  foundBadgeText: {
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryStrong,
  },
  resultDivider: {
    height: 1,
    backgroundColor: colors.outline,
    marginTop: 18,
    marginBottom: 14,
  },
  reminderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reminderText: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.primaryMuted,
    flex: 1,
  },
  voiceReviewContainer: {
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.outline,
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  voiceReviewLabel: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 4,
  },
  voiceReviewText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 21,
    marginBottom: 8,
  },
  voiceCommandError: {
    color: colors.warning,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  errorCard: {
    backgroundColor: colors.errorSoft,
    borderColor: colors.errorOutline,
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  errorText: {
    color: colors.error,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
  },
  retryButton: {
    backgroundColor: colors.primary,
    borderRadius: radii.button,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    alignSelf: 'flex-start',
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  centered: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  helperText: {
    marginTop: 8,
    fontSize: 14,
    color: colors.muted,
  },
  ambiguousContainer: {
    marginTop: 8,
  },
  ambiguousTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
  },
  choiceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.outline,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    minHeight: 60,
  },
  choiceInfo: {
    flex: 1,
  },
  choiceName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  choiceMeta: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 2,
  },
  cardUnknown: {
    backgroundColor: colors.warningSoft,
    borderWidth: 1.5,
    borderColor: colors.warningOutline,
    borderRadius: radii.card,
    padding: 20,
    marginTop: 8,
  },
  unknownTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.warning,
    marginBottom: 6,
  },
  unknownText: {
    fontSize: 15,
    color: colors.text,
    marginBottom: 8,
  },
  unknownHint: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 18,
  },
  emptyContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 15,
    color: colors.muted,
    textAlign: 'center',
    paddingHorizontal: 24,
    lineHeight: 22,
  },
});
