import { StyleSheet } from 'react-native';

export const catalogDictationStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    padding: 12,
  },
  modalCard: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '95%',
    backgroundColor: '#ffffff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 16,
    elevation: 8,
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 12,
    marginBottom: 4,
  },
  title: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: '800',
  },
  subtitle: {
    color: '#64748b',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  content: {
    flexShrink: 1,
  },
  contentInner: {
    paddingBottom: 8,
  },
  typedTranscriptCard: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  sectionTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  fieldLabel: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 5,
    marginTop: 11,
  },
  input: {
    minHeight: 46,
    backgroundColor: '#ffffff',
    borderColor: '#cbd5e1',
    borderWidth: 1,
    borderRadius: 8,
    color: '#0f172a',
    fontSize: 15,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  multilineInput: {
    minHeight: 70,
    textAlignVertical: 'top',
  },
  secondaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    backgroundColor: '#f0f9ff',
    borderColor: '#7dd3fc',
    borderWidth: 1,
    borderRadius: 9,
    marginTop: 9,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  secondaryButtonText: {
    color: '#075985',
    fontSize: 14,
    fontWeight: '700',
  },
  intentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  intentButton: {
    minHeight: 42,
    flexGrow: 1,
    flexBasis: '45%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8fafc',
    borderColor: '#cbd5e1',
    borderWidth: 1,
    borderRadius: 9,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  intentButtonSelected: {
    backgroundColor: '#e0f2fe',
    borderColor: '#0284c7',
  },
  intentButtonText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  intentButtonTextSelected: {
    color: '#075985',
  },
  warningBox: {
    backgroundColor: '#fffbeb',
    borderColor: '#fcd34d',
    borderWidth: 1,
    borderRadius: 9,
    marginBottom: 12,
    padding: 11,
  },
  warningTitle: {
    color: '#92400e',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
  },
  warningText: {
    color: '#92400e',
    fontSize: 13,
    lineHeight: 19,
  },
  fieldsCard: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 14,
    padding: 12,
  },
  selectedProduct: {
    backgroundColor: '#eff6ff',
    borderColor: '#93c5fd',
    borderWidth: 1,
    borderRadius: 9,
    marginTop: 10,
    padding: 11,
  },
  selectedProductTitle: {
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  selectedProductIdentity: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 3,
  },
  selectedProductPrice: {
    color: '#334155',
    fontSize: 13,
    marginTop: 3,
  },
  clearSelectionButton: {
    alignSelf: 'flex-start',
    paddingVertical: 6,
    marginTop: 4,
  },
  clearSelectionText: {
    color: '#075985',
    fontSize: 13,
    fontWeight: '700',
  },
  productChoices: {
    marginTop: 8,
  },
  choiceHint: {
    color: '#64748b',
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 6,
  },
  productChoice: {
    backgroundColor: '#ffffff',
    borderColor: '#cbd5e1',
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 6,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  productChoiceTitle: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '700',
  },
  productChoiceMeta: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
  },
  emptyChoices: {
    color: '#64748b',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  errorBox: {
    backgroundColor: '#fef2f2',
    borderColor: '#fca5a5',
    borderWidth: 1,
    borderRadius: 9,
    marginBottom: 12,
    padding: 11,
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 13,
    lineHeight: 19,
  },
  noticeBox: {
    backgroundColor: '#fffbeb',
    borderColor: '#fcd34d',
    borderWidth: 1,
    borderRadius: 9,
    marginBottom: 12,
    padding: 11,
  },
  noticeText: {
    color: '#92400e',
    fontSize: 13,
    lineHeight: 19,
  },
  proposalCard: {
    backgroundColor: '#f0fdf4',
    borderColor: '#86efac',
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 14,
    padding: 13,
  },
  proposalTitle: {
    color: '#166534',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 7,
  },
  proposalIdentity: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 5,
  },
  proposalRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 4,
  },
  proposalLabel: {
    color: '#475569',
    flex: 1,
    fontSize: 13,
  },
  proposalValue: {
    color: '#0f172a',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'right',
  },
  proposalValueHighlight: {
    color: '#047857',
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'right',
  },
  proposalNote: {
    borderTopColor: '#bbf7d0',
    borderTopWidth: 1,
    color: '#475569',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 7,
    paddingTop: 7,
  },
  confirmSpeechCard: {
    backgroundColor: '#f8fafc',
    borderColor: '#cbd5e1',
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 10,
    padding: 12,
  },
  confirmSpeechHint: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 9,
    paddingTop: 10,
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderColor: '#cbd5e1',
    borderRadius: 9,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 10,
  },
  cancelButtonText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '700',
  },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: '#0284c7',
    borderRadius: 9,
    flex: 1.5,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 10,
  },
  confirmButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
});
