import { colors, radii } from './theme.ts';
import { StyleSheet } from 'react-native';

export const catalogDictationStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.backdrop,
    padding: 12,
  },
  modalCard: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '95%',
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.divider,
    padding: 16,
    elevation: 8,
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
    paddingBottom: 12,
    marginBottom: 4,
  },
  title: {
    color: colors.primaryStrong,
    fontSize: 20,
    fontWeight: '800',
  },
  subtitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  content: {
    flexShrink: 1,
  },
  contentInner: {
    paddingBottom: 8,
  },
  typedTranscriptCard: {
    backgroundColor: colors.background,
    borderColor: colors.divider,
    borderWidth: 1,
    borderRadius: radii.card,
    padding: 12,
    marginBottom: 16,
  },
  sectionTitle: {
    color: colors.primaryStrong,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  fieldLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 5,
    marginTop: 11,
  },
  input: {
    minHeight: 48,
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: radii.field,
    color: colors.primaryStrong,
    fontSize: 15,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  multilineInput: {
    minHeight: 70,
    textAlignVertical: 'top',
  },
  secondaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    backgroundColor: colors.lilac,
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: radii.button,
    marginTop: 9,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  intentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  intentButton: {
    minHeight: 48,
    flexGrow: 1,
    flexBasis: '45%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: radii.button,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  intentButtonSelected: {
    backgroundColor: colors.selected,
    borderColor: colors.primary,
  },
  intentButtonText: {
    color: colors.primaryMuted,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  intentButtonTextSelected: {
    color: colors.primary,
  },
  warningBox: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningOutline,
    borderWidth: 1,
    borderRadius: 9,
    marginBottom: 12,
    padding: 11,
  },
  warningTitle: {
    color: colors.warning,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
  },
  warningText: {
    color: colors.warning,
    fontSize: 13,
    lineHeight: 19,
  },
  fieldsCard: {
    backgroundColor: colors.background,
    borderColor: colors.divider,
    borderWidth: 1,
    borderRadius: radii.card,
    marginBottom: 14,
    padding: 12,
  },
  selectedProduct: {
    backgroundColor: colors.lilac,
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: 9,
    marginTop: 10,
    padding: 11,
  },
  selectedProductTitle: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  selectedProductIdentity: {
    color: colors.primaryStrong,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 3,
  },
  selectedProductPrice: {
    color: colors.text,
    fontSize: 13,
    marginTop: 3,
  },
  clearSelectionButton: {
    alignSelf: 'flex-start',
    paddingVertical: 6,
    marginTop: 4,
  },
  clearSelectionText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
  },
  productChoices: {
    marginTop: 8,
  },
  choiceHint: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 6,
  },
  productChoice: {
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 6,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  productChoiceTitle: {
    color: colors.primaryStrong,
    fontSize: 14,
    fontWeight: '700',
  },
  productChoiceMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  emptyChoices: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  errorBox: {
    backgroundColor: colors.errorSoft,
    borderColor: colors.errorOutline,
    borderWidth: 1,
    borderRadius: 9,
    marginBottom: 12,
    padding: 11,
  },
  errorText: {
    color: colors.error,
    fontSize: 13,
    lineHeight: 19,
  },
  noticeBox: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningOutline,
    borderWidth: 1,
    borderRadius: 9,
    marginBottom: 12,
    padding: 11,
  },
  noticeText: {
    color: colors.warning,
    fontSize: 13,
    lineHeight: 19,
  },
  proposalCard: {
    backgroundColor: colors.successSoft,
    borderColor: colors.successOutline,
    borderWidth: 1,
    borderRadius: radii.card,
    marginBottom: 14,
    padding: 13,
  },
  proposalTitle: {
    color: colors.success,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 7,
  },
  proposalIdentity: {
    color: colors.primaryStrong,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 5,
  },
  proposalRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 4,
  },
  proposalLabel: {
    color: colors.primaryMuted,
    flex: 1,
    fontSize: 13,
  },
  proposalValue: {
    color: colors.primaryStrong,
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'right',
  },
  proposalValueHighlight: {
    color: colors.success,
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'right',
  },
  proposalNote: {
    borderTopColor: colors.successOutline,
    borderTopWidth: 1,
    color: colors.primaryMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 7,
    paddingTop: 7,
  },
  confirmSpeechCard: {
    backgroundColor: colors.background,
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: radii.card,
    marginBottom: 10,
    padding: 12,
  },
  confirmSpeechHint: {
    color: colors.primaryMuted,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 9,
    paddingTop: 10,
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.outline,
    borderRadius: radii.button,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 10,
  },
  cancelButtonText: {
    color: colors.primaryMuted,
    fontSize: 14,
    fontWeight: '700',
  },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radii.button,
    flex: 1.5,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 10,
  },
  confirmButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
});
