import { colors, radii } from './theme.ts';
import { StyleSheet } from 'react-native';

export const manageProductsStyles = StyleSheet.create({
  container: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  subtitle: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 2,
  },
  formCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    padding: 18,
    borderWidth: 1.5,
    borderColor: colors.divider,
    marginBottom: 20,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.primaryStrong,
    marginBottom: 14,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 6,
    marginTop: 10,
  },
  input: {
    minHeight: 48,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.field,
    paddingHorizontal: 12,
    fontSize: 15,
    color: colors.text,
  },
  fieldError: {
    color: colors.error,
    fontSize: 13,
    marginTop: 4,
  },
  reviewBox: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: 10,
    padding: 12,
    marginTop: 16,
  },
  reviewTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryMuted,
    marginBottom: 8,
  },
  reviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
  },
  reviewLabel: {
    fontSize: 13,
    color: colors.muted,
  },
  reviewValue: {
    flex: 1,
    textAlign: 'right',
    marginLeft: 12,
    fontSize: 13,
    fontWeight: '600',
    color: colors.primaryStrong,
  },
  reviewPrice: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  errorBox: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  errorText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: '500',
  },
  successBox: {
    backgroundColor: colors.successSoft,
    borderWidth: 1,
    borderColor: colors.successOutline,
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  successText: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '600',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.outline,
    minHeight: 52,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cancelButtonText: {
    color: colors.primaryMuted,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  saveButton: {
    flex: 1.5,
    backgroundColor: colors.primary,
    minHeight: 52,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  saveButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  saveButtonText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  listCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    padding: 18,
    borderWidth: 1.5,
    borderColor: colors.divider,
  },
  emptyListText: {
    color: colors.muted,
    fontSize: 14,
    marginTop: 4,
  },
  productRow: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceSoft,
  },
  productHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  productInfo: {
    flex: 1,
    marginRight: 10,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  itemMeta: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 2,
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.primary,
  },
  stockBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
  },
  stockBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  stockBadgePresent: {
    backgroundColor: colors.successSoft,
    borderWidth: 1,
    borderColor: colors.successOutline,
  },
  stockBadgeTextPresent: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.success,
  },
  stockBadgeUncounted: {
    backgroundColor: colors.warningSoft,
    borderWidth: 1,
    borderColor: colors.warningOutline,
  },
  stockBadgeTextUncounted: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.warning,
  },
  productActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  actionChip: {
    minHeight: 48,
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
  },
  actionChipPrimary: {
    borderColor: colors.outline,
    backgroundColor: colors.lilac,
  },
  actionChipPrimaryText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    textAlign: 'center',
  },
});

