import { colors, radii } from './theme.ts';
import { StyleSheet } from 'react-native';

export const repaymentModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.backdrop,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    width: '100%',
    maxWidth: 520,
    maxHeight: '90%',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHeader: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceSoft,
    backgroundColor: colors.background,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  customerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  customerSubtitle: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  closeBtn: {
    minWidth: 48,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 6,
    borderRadius: radii.button,
    backgroundColor: colors.divider,
  },
  closeBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryMuted,
  },
  balanceBanner: {
    marginTop: 10,
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  balanceBannerLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.error,
  },
  balanceBannerValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.error,
  },
  tabsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
    backgroundColor: colors.background,
  },
  tabBtn: {
    minHeight: 48,
    justifyContent: 'center',
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabBtnActive: {
    borderBottomColor: colors.primary,
    backgroundColor: colors.surface,
  },
  tabBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.muted,
  },
  tabBtnTextActive: {
    color: colors.primary,
    fontWeight: '800',
  },
  scrollBody: {
    padding: 20,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 6,
  },
  input: {
    minHeight: 48,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.outline,
    borderRadius: radii.field,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.primaryStrong,
  },
  quickPayRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 6,
  },
  quickPayBtn: {
    minHeight: 48,
    justifyContent: 'center',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radii.button,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  quickPayBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  paymentMethodRow: {
    flexDirection: 'row',
    gap: 10,
  },
  methodBtn: {
    minHeight: 48,
    justifyContent: 'center',
    flex: 1,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderColor: colors.outline,
    borderRadius: radii.button,
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  methodBtnActive: {
    borderColor: colors.primary,
    backgroundColor: colors.lilac,
  },
  methodBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primaryMuted,
  },
  methodBtnTextActive: {
    color: colors.primary,
    fontWeight: '800',
  },
  previewCard: {
    backgroundColor: colors.successSoft,
    borderWidth: 1.5,
    borderColor: colors.successOutline,
    borderRadius: radii.card,
    padding: 14,
    marginBottom: 16,
  },
  previewTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.success,
    marginBottom: 10,
  },
  previewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
  },
  previewLabel: {
    fontSize: 13,
    color: colors.success,
  },
  previewValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.success,
  },
  allocationsSection: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.successOutline,
  },
  allocationsHeader: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.success,
    marginBottom: 6,
  },
  allocationItem: {
    backgroundColor: colors.surface,
    borderRadius: 6,
    padding: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.successSoft,
  },
  allocTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  allocDesc: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primaryStrong,
    flex: 1,
  },
  allocBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  allocBadgeSettled: {
    backgroundColor: colors.successSoft,
  },
  allocBadgePartial: {
    backgroundColor: colors.warningSoft,
  },
  allocBadgeTextSettled: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.success,
  },
  allocBadgeTextPartial: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.warning,
  },
  allocDetailText: {
    fontSize: 11,
    color: colors.muted,
    marginTop: 3,
  },
  errorBox: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
  },
  errorText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: '600',
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 10,
    marginBottom: 20,
  },
  cancelBtn: {
    minHeight: 48,
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: radii.button,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: colors.surface,
  },
  cancelBtnText: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryMuted,
  },
  confirmBtn: {
    minHeight: 48,
    paddingHorizontal: 12,
    flex: 1,
    paddingVertical: 12,
    borderRadius: radii.button,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmBtnDisabled: {
    backgroundColor: colors.disabled,
  },
  confirmBtnText: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '800',
    color: colors.surface,
  },
  // History tab styles
  historySection: {
    marginBottom: 16,
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 8,
  },
  emptyHistoryText: {
    fontSize: 12,
    color: colors.disabled,
    fontStyle: 'italic',
    paddingVertical: 6,
  },
  historyCard: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: radii.card,
    padding: 10,
    marginBottom: 8,
  },
  historyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryStrong,
  },
  historyAmount: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.primary,
  },
  historyDate: {
    fontSize: 11,
    color: colors.muted,
    marginTop: 3,
  },
  reversedBadge: {
    backgroundColor: '#fee2e2',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  reversedBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.error,
  },
  reversalReasonText: {
    fontSize: 11,
    color: colors.error,
    fontStyle: 'italic',
    marginTop: 2,
  },
  reverseBtn: {
    minHeight: 48,
    justifyContent: 'center',
    backgroundColor: '#fee2e2',
    borderWidth: 1,
    borderColor: colors.errorOutline,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radii.button,
    alignSelf: 'flex-start',
    marginTop: 6,
  },
  reverseBtnText: {
    color: colors.error,
    fontSize: 14,
    fontWeight: '700',
  },
  reversalConfirmBox: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#fecdd3',
    borderRadius: 6,
    padding: 8,
    marginTop: 8,
  },
  reversalConfirmPrompt: {
    fontSize: 12,
    fontWeight: '700',
    color: '#9f1239',
    marginBottom: 6,
  },
  reversalInput: {
    minHeight: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.field,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 12,
    color: colors.text,
    marginBottom: 6,
  },
  reversalActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
  },
  reversalCancelBtn: {
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  reversalCancelBtnText: {
    fontSize: 14,
    color: colors.muted,
    fontWeight: '600',
  },
  reversalConfirmBtn: {
    minHeight: 48,
    justifyContent: 'center',
    backgroundColor: colors.error,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radii.button,
  },
  reversalConfirmBtnText: {
    fontSize: 14,
    color: colors.surface,
    fontWeight: '700',
  },
});
