import { colors, radii } from './theme.ts';
import { StyleSheet } from 'react-native';

export const restockChecklistStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.backdrop,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 14,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    padding: 18,
    width: '100%',
    maxWidth: 520,
    maxHeight: '92%',
    borderWidth: 1,
    borderColor: colors.divider,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceSoft,
    paddingBottom: 10,
    marginBottom: 12,
  },
  titleCol: {
    flex: 1,
    marginRight: 10,
  },
  modalTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  modalSubtitle: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 2,
    fontWeight: '500',
  },
  closeButton: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: colors.surfaceSoft,
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.muted,
  },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginTop: 6,
  },
  statusBadgeDraft: {
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  statusBadgeApproved: {
    backgroundColor: colors.successSoft,
    borderWidth: 1,
    borderColor: colors.successOutline,
  },
  statusBadgeDiscarded: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  aiBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.lilac,
    borderRadius: radii.field,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  aiBarText: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
    flex: 1,
  },
  aiButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  aiButtonText: {
    fontSize: 12,
    color: colors.surface,
    fontWeight: '700',
  },
  banner: {
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  bannerDraft: {
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  bannerApproved: {
    backgroundColor: colors.successSoft,
    borderWidth: 1,
    borderColor: colors.successOutline,
  },
  bannerText: {
    fontSize: 12,
    lineHeight: 17,
    color: colors.text,
    fontWeight: '500',
  },
  bannerBold: {
    fontWeight: '700',
    color: colors.primaryStrong,
  },
  itemsList: {
    maxHeight: 340,
    marginBottom: 12,
  },
  itemCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  itemCardPriority: {
    borderColor: colors.primary,
    backgroundColor: colors.lilac,
  },
  itemCardExcluded: {
    opacity: 0.5,
    backgroundColor: colors.surfaceSoft,
  },
  itemHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemTitleContainer: {
    flex: 1,
    marginRight: 8,
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  itemMeta: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 1,
  },
  priorityBadge: {
    backgroundColor: colors.primary,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  priorityBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.surface,
  },
  checkboxButton: {
    minWidth: 44,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  checkboxBoxChecked: {
    backgroundColor: colors.primary,
  },
  checkboxCheckText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '800',
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginVertical: 6,
  },
  tagBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  tagOutOfStock: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
  },
  tagLowStock: {
    backgroundColor: colors.warningSoft,
    borderWidth: 1,
    borderColor: colors.warningOutline,
  },
  tagUncounted: {
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  tagPopular: {
    backgroundColor: colors.lilac,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  tagText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.text,
  },
  historyText: {
    fontSize: 11,
    color: colors.muted,
    fontStyle: 'italic',
    marginTop: 2,
  },
  quantityControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceSoft,
  },
  quantityLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  counterButton: {
    minWidth: 40,
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.outline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primaryStrong,
  },
  counterInput: {
    minWidth: 44,
    minHeight: 40,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: 8,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    backgroundColor: colors.surface,
    paddingHorizontal: 4,
  },
  deliveryButton: {
    backgroundColor: colors.success,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deliveryButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.surface,
  },
  emptyContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: colors.muted,
    textAlign: 'center',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceSoft,
    paddingTop: 12,
  },
  approveButton: {
    flex: 2,
    minHeight: 48,
    backgroundColor: colors.primary,
    borderRadius: radii.button,
    alignItems: 'center',
    justifyContent: 'center',
  },
  approveButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.surface,
  },
  discardButton: {
    flex: 1,
    minHeight: 48,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.button,
    alignItems: 'center',
    justifyContent: 'center',
  },
  discardButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.error,
  },
  closeFooterButton: {
    flex: 1,
    minHeight: 48,
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.button,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeFooterButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  removeItemButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
  },
  removeItemButtonText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.error,
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radii.button,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.accent,
    borderStyle: 'dashed',
    marginVertical: 10,
  },
  addItemButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.accent,
  },
  sectionHeader: {
    marginTop: 14,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  sectionHeaderText: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  pickerCard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.card,
    padding: 12,
    marginTop: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  pickerTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  pickerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: colors.surface,
    borderRadius: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  pickerItemName: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  pickerItemMeta: {
    fontSize: 11,
    color: colors.muted,
  },
});
