import { colors, radii } from './theme.ts';
import { StyleSheet } from 'react-native';

export const sellStyles = StyleSheet.create({
  container: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  subtitle: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 2,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    padding: 18,
    borderWidth: 1.5,
    borderColor: colors.divider,
    marginBottom: 16,
  },
  sectionHeader: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.primaryStrong,
    marginBottom: 12,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    minHeight: 48,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.field,
    paddingHorizontal: 12,
    fontSize: 14,
    color: colors.text,
  },
  catalogScroll: {
    maxHeight: 180,
  },
  catalogItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceSoft,
  },
  catalogItemInfo: {
    flex: 1,
    marginRight: 8,
  },
  catalogItemName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  catalogItemMeta: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  catalogItemStock: {
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  stockOk: {
    color: colors.success,
  },
  stockNone: {
    color: colors.warning,
  },
  catalogItemPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    marginRight: 10,
  },
  addButton: {
    backgroundColor: colors.primary,
    minHeight: 48,
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '700',
  },
  emptyText: {
    color: colors.muted,
    fontSize: 13,
    paddingVertical: 12,
    textAlign: 'center',
  },
  cartTable: {
    marginBottom: 12,
  },
  cartItemRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceSoft,
  },
  cartItemDetails: {
    width: '100%',
  },
  cartItemTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  cartItemUnitPrice: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  cartItemStockWarning: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.error,
    marginTop: 2,
  },
  cartQuantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qtyButton: {
    backgroundColor: colors.surfaceSoft,
    minWidth: 48,
    minHeight: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.outline,
  },
  qtyButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  qtyText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryStrong,
    minWidth: 20,
    textAlign: 'center',
  },
  cartSubtotal: {
    flex: 1,
    flexShrink: 1,
    minWidth: 72,
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    textAlign: 'right',
  },
  deleteButton: {
    minWidth: 48,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  deleteButtonText: {
    color: colors.error,
    fontSize: 14,
    fontWeight: '700',
  },
  checkoutSummary: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: 12,
    padding: 14,
    marginTop: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  summaryLabel: {
    fontSize: 14,
    color: colors.primaryMuted,
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primaryStrong,
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: colors.outline,
    marginTop: 6,
    paddingTop: 8,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  totalValue: {
    fontSize: 18,
    fontWeight: '900',
    color: colors.primary,
  },
  tenderSection: {
    marginTop: 12,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 6,
  },
  tenderInput: {
    minHeight: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.field,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  changeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.successSoft,
    borderWidth: 1,
    borderColor: colors.successOutline,
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
  },
  changeLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.success,
  },
  changeValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.success,
  },
  errorBox: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  errorText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: '600',
  },
  successBox: {
    backgroundColor: colors.successSoft,
    borderWidth: 1,
    borderColor: colors.successOutline,
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  successTitle: {
    color: colors.success,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  successDetail: {
    color: colors.success,
    fontSize: 13,
  },
  confirmButton: {
    backgroundColor: colors.primary,
    minHeight: 50,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
  },
  confirmButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  confirmButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '800',
  },
  paymentMethodRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
    marginBottom: 10,
  },
  paymentTab: {
    flex: 1,
    minHeight: 48,
    minWidth: 48,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: colors.outline,
    backgroundColor: colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  paymentTabActive: {
    borderColor: colors.primary,
    backgroundColor: colors.lilac,
  },
  paymentTabText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryMuted,
  },
  paymentTabTextActive: {
    color: colors.primary,
  },
  pendingBanner: {
    backgroundColor: colors.warningSoft,
    borderWidth: 1.5,
    borderColor: colors.warningOutline,
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
  },
  pendingBannerTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.warning,
    marginBottom: 4,
  },
  pendingBannerText: {
    fontSize: 13,
    color: colors.warning,
    lineHeight: 18,
  },
  draftCard: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: radii.card,
    padding: 12,
    marginTop: 10,
  },
  draftHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  draftRef: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  draftTotal: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  draftActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  draftConfirmBtn: {
    flex: 2,
    backgroundColor: colors.success,
    minHeight: 48,
    minWidth: 48,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
  },
  draftConfirmText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '700',
  },
  draftCancelBtn: {
    flex: 1,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.outline,
    minHeight: 48,
    minWidth: 48,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
  },
  draftCancelText: {
    color: colors.primaryMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  customerSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  customerList: {
    maxHeight: 140,
    marginTop: 6,
  },
  customerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: 8,
    marginBottom: 6,
    backgroundColor: colors.surface,
  },
  customerItemSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.lilac,
  },
  customerName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  customerNote: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  customerDebt: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.error,
  },
  customerDebtContainer: {
    alignItems: 'flex-end',
    gap: 4,
  },
  repayButton: {
    backgroundColor: colors.primary,
    minHeight: 48,
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
  },
  repayButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '700',
  },
  newCustomerRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  newCustomerInput: {
    flex: 1,
    minHeight: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.field,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    color: colors.text,
  },
  newCustomerBtn: {
    backgroundColor: colors.primary,
    minHeight: 48,
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: radii.button,
  },
  newCustomerBtnText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '700',
  },
  creditBreakdown: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
  },
  creditBreakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  creditBreakdownLabel: {
    fontSize: 13,
    color: colors.error,
  },
  creditBreakdownValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.error,
  },
  // Recent Sales styles
  recentSaleItem: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  recentSaleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recentSaleTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryStrong,
  },
  recentSaleAmount: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.primary,
  },
  recentSaleMeta: {
    fontSize: 11,
    color: colors.muted,
    marginTop: 2,
  },
  cancelledBadge: {
    backgroundColor: colors.errorSoft,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  cancelledBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.error,
  },
  cancelledReasonText: {
    fontSize: 11,
    color: colors.error,
    fontStyle: 'italic',
    marginTop: 3,
  },
  cancelSaleBtn: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    minHeight: 48,
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.button,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 6,
  },
  cancelSaleBtnText: {
    color: colors.error,
    fontSize: 14,
    fontWeight: '700',
  },
  cancelConfirmBox: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    borderRadius: 6,
    padding: 8,
    marginTop: 8,
  },
  cancelConfirmPrompt: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.error,
    marginBottom: 4,
  },
  cancelConfirmWarning: {
    fontSize: 11,
    color: colors.error,
    marginBottom: 6,
  },
  cancelInput: {
    minHeight: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.field,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    color: colors.text,
    marginBottom: 6,
  },
  cancelActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
  },
  cancelCancelBtn: {
    maxWidth: '100%',
    minHeight: 48,
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: radii.button,
  },
  cancelCancelBtnText: {
    textAlign: 'center',
    fontSize: 14,
    color: colors.muted,
    fontWeight: '600',
  },
  cancelConfirmBtn: {
    maxWidth: '100%',
    backgroundColor: colors.error,
    minHeight: 48,
    minWidth: 48,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelConfirmBtnText: {
    textAlign: 'center',
    fontSize: 14,
    color: colors.surface,
    fontWeight: '700',
  },
});


