import { StyleSheet } from 'react-native';

export const sellStyles = StyleSheet.create({
  container: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
  },
  subtitle: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 2,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    marginBottom: 16,
  },
  sectionHeader: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 12,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    minHeight: 46,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    color: '#1e293b',
  },
  catalogScroll: {
    maxHeight: 180,
  },
  catalogItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  catalogItemInfo: {
    flex: 1,
    marginRight: 8,
  },
  catalogItemName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
  },
  catalogItemMeta: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  catalogItemStock: {
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  stockOk: {
    color: '#059669',
  },
  stockNone: {
    color: '#b45309',
  },
  catalogItemPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0284c7',
    marginRight: 10,
  },
  addButton: {
    backgroundColor: '#0284c7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  addButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  emptyText: {
    color: '#94a3b8',
    fontSize: 13,
    paddingVertical: 12,
    textAlign: 'center',
  },
  cartTable: {
    marginBottom: 12,
  },
  cartItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  cartItemDetails: {
    flex: 1,
    marginRight: 8,
  },
  cartItemTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
  },
  cartItemUnitPrice: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  cartItemStockWarning: {
    fontSize: 11,
    fontWeight: '700',
    color: '#dc2626',
    marginTop: 2,
  },
  cartQuantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  qtyButton: {
    backgroundColor: '#f1f5f9',
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  qtyButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#334155',
  },
  qtyText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
    minWidth: 20,
    textAlign: 'center',
  },
  cartSubtotal: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0284c7',
    minWidth: 60,
    textAlign: 'right',
  },
  deleteButton: {
    paddingLeft: 8,
    paddingVertical: 4,
  },
  deleteButtonText: {
    color: '#dc2626',
    fontSize: 14,
    fontWeight: '700',
  },
  checkoutSummary: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 14,
    marginTop: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#475569',
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0f172a',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#cbd5e1',
    marginTop: 6,
    paddingTop: 8,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  totalValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0284c7',
  },
  tenderSection: {
    marginTop: 12,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 6,
  },
  tenderInput: {
    minHeight: 46,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: '700',
    color: '#1e293b',
  },
  changeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
  },
  changeLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#065f46',
  },
  changeValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#059669',
  },
  errorBox: {
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fca5a5',
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 13,
    fontWeight: '600',
  },
  successBox: {
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#86efac',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  successTitle: {
    color: '#15803d',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  successDetail: {
    color: '#166534',
    fontSize: 13,
  },
  confirmButton: {
    backgroundColor: '#0284c7',
    minHeight: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
  },
  confirmButtonDisabled: {
    backgroundColor: '#94a3b8',
  },
  confirmButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  paymentMethodRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
    marginBottom: 10,
  },
  paymentTab: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentTabActive: {
    borderColor: '#0284c7',
    backgroundColor: '#f0f9ff',
  },
  paymentTabText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#475569',
  },
  paymentTabTextActive: {
    color: '#0284c7',
  },
  pendingBanner: {
    backgroundColor: '#fffbeb',
    borderWidth: 1.5,
    borderColor: '#fde68a',
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
  },
  pendingBannerTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#92400e',
    marginBottom: 4,
  },
  pendingBannerText: {
    fontSize: 13,
    color: '#b45309',
    lineHeight: 18,
  },
  draftCard: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 12,
    marginTop: 10,
  },
  draftHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  draftRef: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0369a1',
  },
  draftTotal: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0f172a',
  },
  draftActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  draftConfirmBtn: {
    flex: 2,
    backgroundColor: '#059669',
    paddingVertical: 8,
    borderRadius: 6,
    alignItems: 'center',
  },
  draftConfirmText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  draftCancelBtn: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingVertical: 8,
    borderRadius: 6,
    alignItems: 'center',
  },
  draftCancelText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '600',
  },
  customerSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  customerList: {
    maxHeight: 140,
    marginTop: 6,
  },
  customerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    marginBottom: 6,
    backgroundColor: '#ffffff',
  },
  customerItemSelected: {
    borderColor: '#0284c7',
    backgroundColor: '#f0f9ff',
  },
  customerName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
  },
  customerNote: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  customerDebt: {
    fontSize: 13,
    fontWeight: '700',
    color: '#b91c1c',
  },
  newCustomerRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  newCustomerInput: {
    flex: 1,
    minHeight: 40,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 6,
    paddingHorizontal: 10,
    fontSize: 13,
    color: '#1e293b',
  },
  newCustomerBtn: {
    backgroundColor: '#0284c7',
    paddingHorizontal: 12,
    justifyContent: 'center',
    borderRadius: 6,
  },
  newCustomerBtnText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  creditBreakdown: {
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
  },
  creditBreakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  creditBreakdownLabel: {
    fontSize: 13,
    color: '#991b1b',
  },
  creditBreakdownValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#b91c1c',
  },
});


