import { StyleSheet } from 'react-native';

export const speechTranscriptStyles = StyleSheet.create({
  container: {
    backgroundColor: '#ffffff',
    borderColor: '#bae6fd',
    borderWidth: 1.5,
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
  },
  title: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  description: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  statusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    minHeight: 24,
  },
  statusText: {
    color: '#334155',
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#0284c7',
    borderRadius: 10,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#f0f9ff',
    borderColor: '#7dd3fc',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 46,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: '#075985',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  holdButton: {
    alignItems: 'center',
    backgroundColor: '#eff6ff',
    borderColor: '#60a5fa',
    borderRadius: 12,
    borderWidth: 1.5,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 74,
    padding: 12,
  },
  microphoneIcon: {
    fontSize: 22,
  },
  holdButtonText: {
    color: '#1e3a8a',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 3,
    textAlign: 'center',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ed',
    borderColor: '#fdba74',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 44,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  cancelButtonText: {
    color: '#9a3412',
    fontSize: 14,
    fontWeight: '700',
  },
  errorBox: {
    backgroundColor: '#fff7ed',
    borderColor: '#fdba74',
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 10,
    padding: 12,
  },
  errorText: {
    color: '#9a3412',
    fontSize: 14,
    lineHeight: 20,
  },
  settingsButton: {
    alignItems: 'center',
    backgroundColor: '#ffedd5',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  settingsError: {
    color: '#9a3412',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  transcriptSection: {
    borderTopColor: '#e2e8f0',
    borderTopWidth: 1,
    marginTop: 16,
    paddingTop: 14,
  },
  transcriptLabel: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 6,
  },
  recognizedText: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
    borderRadius: 8,
    borderWidth: 1,
    color: '#475569',
    fontSize: 15,
    lineHeight: 21,
    marginBottom: 12,
    minHeight: 44,
    padding: 10,
  },
  partialTranscript: {
    color: '#475569',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 20,
    marginTop: 8,
  },
  transcriptInput: {
    backgroundColor: '#ffffff',
    borderColor: '#94a3b8',
    borderRadius: 8,
    borderWidth: 1.5,
    color: '#0f172a',
    fontSize: 16,
    lineHeight: 23,
    minHeight: 84,
    padding: 10,
  },
  reviewedNotice: {
    color: '#166534',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 12,
    textAlign: 'center',
  },
  discardButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 42,
    padding: 8,
  },
  discardButtonText: {
    color: '#b91c1c',
    fontSize: 14,
    fontWeight: '700',
  },
});
