import { StyleSheet } from 'react-native';
import { colors, radii } from './theme.ts';

export const speechTranscriptStyles = StyleSheet.create({
  container: {
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderWidth: 1.5,
    borderRadius: radii.card,
    padding: 16,
    marginBottom: 20,
  },
  compactContainer: {
    marginBottom: 12,
  },
  compactSpeechButton: {
    minHeight: 56,
    backgroundColor: colors.accent,
    borderRadius: radii.button,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 8,
  },
  compactSpeechButtonText: {
    flexShrink: 1,
    textAlign: 'center',
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  accessibleButton: {
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginTop: 4,
  },
  accessibleButtonText: {
    textAlign: 'center',
    color: colors.primaryMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  title: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '800',
  },
  description: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  statusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    minHeight: 24,
  },
  statusText: {
    color: colors.muted,
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: radii.button,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  primaryButtonText: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.outline,
    borderRadius: radii.button,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  holdButton: {
    alignItems: 'center',
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
    borderRadius: radii.button,
    borderWidth: 1.5,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 74,
    padding: 12,
  },
  holdButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
    textAlign: 'center',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningOutline,
    borderRadius: radii.button,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  cancelButtonText: {
    color: colors.warning,
    fontSize: 14,
    fontWeight: '700',
  },
  errorBox: {
    backgroundColor: colors.errorSoft,
    borderColor: colors.errorOutline,
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 10,
    padding: 12,
  },
  errorText: {
    color: colors.error,
    fontSize: 14,
    lineHeight: 20,
  },
  settingsButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: radii.button,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  settingsError: {
    color: colors.error,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  transcriptSection: {
    borderTopColor: colors.divider,
    borderTopWidth: 1,
    marginTop: 16,
    paddingTop: 14,
  },
  transcriptLabel: {
    color: colors.primaryMuted,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 6,
  },
  recognizedText: {
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.outline,
    borderRadius: radii.field,
    borderWidth: 1,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 21,
    marginBottom: 12,
    minHeight: 48,
    padding: 10,
  },
  partialTranscript: {
    color: colors.muted,
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 20,
    marginTop: 8,
  },
  transcriptInput: {
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderRadius: radii.field,
    borderWidth: 1.5,
    color: colors.text,
    fontSize: 16,
    lineHeight: 23,
    minHeight: 84,
    padding: 10,
  },
  reviewedNotice: {
    color: colors.success,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 12,
    textAlign: 'center',
  },
  discardButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 48,
    minWidth: 48,
    padding: 8,
  },
  discardButtonText: {
    color: colors.error,
    fontSize: 14,
    fontWeight: '700',
  },
});
