import { StyleSheet } from 'react-native';

export const spokenOrderStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  card: {
    maxHeight: '94%',
    backgroundColor: '#f8fafc',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  title: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: '800',
    flex: 1,
    marginRight: 8,
  },
  closeButton: {
    minHeight: 44,
    minWidth: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#e2e8f0',
    paddingHorizontal: 10,
  },
  closeButtonText: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
  },
  subtitle: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  section: {
    backgroundColor: '#ffffff',
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
  },
  sectionTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  cartLine: {
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  cartName: {
    color: '#1e293b',
    fontSize: 14,
    fontWeight: '700',
  },
  cartMeta: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
  },
  emptyText: {
    color: '#64748b',
    fontSize: 13,
    lineHeight: 19,
  },
  input: {
    minHeight: 44,
    backgroundColor: '#ffffff',
    borderColor: '#94a3b8',
    borderWidth: 1,
    borderRadius: 8,
    color: '#0f172a',
    fontSize: 15,
    paddingHorizontal: 10,
    marginTop: 6,
  },
  commandInput: {
    minHeight: 78,
    textAlignVertical: 'top',
    paddingVertical: 10,
  },
  itemCard: {
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginTop: 8,
    backgroundColor: '#f8fafc',
  },
  query: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '800',
  },
  message: {
    color: '#9a3412',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  fieldLabel: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
  },
  choice: {
    alignItems: 'flex-start',
    borderColor: '#cbd5e1',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    padding: 9,
    marginTop: 6,
  },
  choiceSelected: {
    borderColor: '#0284c7',
    backgroundColor: '#f0f9ff',
  },
  choiceTitle: {
    color: '#1e293b',
    fontSize: 13,
    fontWeight: '700',
  },
  choiceMeta: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
  },
  errorBox: {
    backgroundColor: '#fff7ed',
    borderColor: '#fdba74',
    borderWidth: 1,
    borderRadius: 9,
    padding: 10,
    marginTop: 10,
  },
  errorText: {
    color: '#9a3412',
    fontSize: 13,
    lineHeight: 19,
  },
  note: {
    color: '#475569',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopColor: '#cbd5e1',
    borderTopWidth: 1,
    marginTop: 8,
    paddingTop: 9,
  },
  totalLabel: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '800',
  },
  totalValue: {
    color: '#0369a1',
    fontSize: 16,
    fontWeight: '900',
  },
  actions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 9,
    backgroundColor: '#e2e8f0',
    paddingHorizontal: 10,
  },
  secondaryButtonText: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
  },
  primaryButton: {
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 9,
    backgroundColor: '#0284c7',
    paddingHorizontal: 10,
  },
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  launcher: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eff6ff',
    borderColor: '#93c5fd',
    borderWidth: 1,
    borderRadius: 9,
    minHeight: 48,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  launcherDisabled: {
    opacity: 0.5,
  },
  launcherText: {
    color: '#1d4ed8',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
});
