import { colors, radii } from './theme.ts';
import { StyleSheet } from 'react-native';

export const spokenOrderStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.backdrop,
  },
  card: {
    maxHeight: '94%',
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  title: {
    color: colors.primaryStrong,
    fontSize: 20,
    fontWeight: '800',
    flex: 1,
    marginRight: 8,
  },
  closeButton: {
    minHeight: 48,
    minWidth: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.button,
    backgroundColor: colors.divider,
    paddingHorizontal: 10,
  },
  closeButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  subtitle: {
    color: colors.primaryMuted,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  section: {
    backgroundColor: colors.surface,
    borderColor: colors.divider,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
  },
  sectionTitle: {
    color: colors.primaryStrong,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  cartLine: {
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceSoft,
  },
  cartName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  cartMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  emptyText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  input: {
    minHeight: 48,
    backgroundColor: colors.surface,
    borderColor: colors.disabled,
    borderWidth: 1,
    borderRadius: radii.field,
    color: colors.primaryStrong,
    fontSize: 15,
    paddingHorizontal: 10,
    marginTop: 6,
  },
  commandInput: {
    minHeight: 78,
    textAlignVertical: 'top',
    paddingVertical: 10,
  },
  itemCard: {
    borderColor: colors.divider,
    borderWidth: 1,
    borderRadius: radii.card,
    padding: 10,
    marginTop: 8,
    backgroundColor: colors.background,
  },
  query: {
    color: colors.primaryStrong,
    fontSize: 14,
    fontWeight: '800',
  },
  message: {
    color: colors.warning,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  fieldLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
  },
  choice: {
    alignItems: 'flex-start',
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 9,
    marginTop: 6,
  },
  choiceSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.lilac,
  },
  choiceTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  choiceMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  errorBox: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningOutline,
    borderWidth: 1,
    borderRadius: 9,
    padding: 10,
    marginTop: 10,
  },
  errorText: {
    color: colors.warning,
    fontSize: 13,
    lineHeight: 19,
  },
  note: {
    color: colors.primaryMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopColor: colors.outline,
    borderTopWidth: 1,
    marginTop: 8,
    paddingTop: 9,
  },
  totalLabel: {
    color: colors.primaryStrong,
    fontSize: 14,
    fontWeight: '800',
  },
  totalValue: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '900',
  },
  actions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: radii.button,
    backgroundColor: colors.divider,
    paddingHorizontal: 10,
  },
  secondaryButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  primaryButton: {
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: radii.button,
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
  },
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  launcher: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lilac,
    borderColor: colors.outline,
    borderWidth: 1,
    borderRadius: 9,
    minHeight: 48,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  launcherDisabled: {
    opacity: 0.5,
  },
  launcherText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
});
