import { colors, radii } from './theme.ts';
import { StyleSheet } from 'react-native';

export const stockActionStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.backdrop,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    padding: 20,
    width: '100%',
    maxWidth: 480,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: colors.divider,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHeader: {
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceSoft,
    paddingBottom: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.primaryStrong,
  },
  modalSubtitle: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 2,
    fontWeight: '500',
  },
  productBadge: {
    backgroundColor: colors.lilac,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 10,
  },
  productBadgeTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
  },
  productBadgeMeta: {
    fontSize: 13,
    color: colors.primary,
    marginTop: 2,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    minHeight: 48,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: radii.field,
    paddingHorizontal: 12,
    fontSize: 15,
    color: colors.text,
  },
  fieldError: {
    color: colors.error,
    fontSize: 13,
    marginTop: 4,
  },
  previewCard: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: radii.card,
    padding: 14,
    marginTop: 16,
  },
  previewTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryMuted,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  previewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  previewLabel: {
    fontSize: 13,
    color: colors.muted,
  },
  previewValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryStrong,
  },
  previewValueHighlight: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.primary,
  },
  previewNote: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    fontSize: 12,
    color: colors.muted,
    fontStyle: 'italic',
  },
  errorBox: {
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.errorOutline,
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  errorText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: '500',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.outline,
    minHeight: 48,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: colors.primaryMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  confirmButton: {
    flex: 1.5,
    backgroundColor: colors.primary,
    minHeight: 48,
    borderRadius: radii.button,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  confirmButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '700',
  },
  historyList: {
    marginTop: 8,
    maxHeight: 280,
  },
  historyItem: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  historyTypeBadge: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
    backgroundColor: colors.selected,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  historyDate: {
    fontSize: 11,
    color: colors.disabled,
  },
  historyFlow: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    marginTop: 2,
  },
  historyNote: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 4,
    fontStyle: 'italic',
  },
  emptyHistoryText: {
    textAlign: 'center',
    color: colors.disabled,
    fontSize: 14,
    paddingVertical: 24,
  },
});
